services:
  - type: web
    name: springboot-app
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile

  - type: web
    name: react-ui
    env: docker
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
