services:
  - type: web
    name: springboot-app
    env: docker
    dockerContext: ./backend
    # Dockerfile is at /backend/Dockerfile
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SPRING_AI_OPENAI_API_KEY
        generate: true

  - type: web
    name: react-ui
    env: docker
    dockerContext: ./frontend
    # Dockerfile is at /frontend/Dockerfile
    dockerfilePath: ./frontend/Dockerfile
